!
Subroutine abdiddpn(Rcut,Rstart)
!Collects alfa(q),beta(q),did(q),dpn(q) (used in EnConfig()) in file 551. With the use of abdiddpn(..), alfa(q),beta(q),did(q),dpn(q) are those obtained in the initial config.
use DataType
integer, parameter :: dp = kind(1.0d0)
Real(dp):: T240(N13,8),TT240(N13,8),T260(N2IN,8),TT260(N2IN,8),TT280(N4OUT,8),T280(N4OUT,8) !reshaped T1,T2,T3.
Real(dp)::alfa1(N13,5:8),beta1(N13,5:8),did1(N13,5:8) !elastic parameters,bulk distance between Ga (PA) atoms and NA (Sb orAs).
Real(dp)::alfa2(N13+1:N13+N2IN,5:8),beta2(N13+1:N13+N2IN,5:8),did2(N13+1:N13+N2IN,5:8) !elastic parameters,bulk distance between Sb atoms (PA) and Ga (NA).
Real(dp)::alfa3(N13+N2IN+1:N13+N2IN+N4OUT,5:8),beta3(N13+N2IN+1:N13+N2IN+N4OUT,5:8),did3(N13+N2IN+1:N13+N2IN+N4OUT,5:8) !elastic parameters,bulk distance between, e.g., As atoms (PA) and Ga (NA).
Real(dp):: alfa(4*(N13+N2IN+N4OUT)),beta(4*(N13+N2IN+N4OUT)),did(4*(N13+N2IN+N4OUT)),dpn(4*(N13+N2IN+N4OUT))
      Integer:: TTNb1(N13,8),TNb1(N13,8),TTNb2(N2IN,8),TNb2(N2IN,8),TTNb3(N4OUT,8),TNb3(N4OUT,8)
      Integer:: TTNb(N13+N2IN+N4OUT,5),TNb(N13+N2IN+N4OUT,5)
      Integer::i,j,t, Rstart
      Logical::Logs23(N13,5:8)
      Real(dp)::  Rcut(Rstart)
integer:: q,jj,ii
!continue
!""""""""""""""""""""""""""""""""""""""""""""""
!
    rewind(111) !file 111 provides the indexes of each atom and its first 4 neighbors for the initial configuration
    read(111,*)TTNb
    TNb=RESHAPE(TTNb, (/N13+N2IN+N4OUT,5/), ORDER = (/2,1/)) !TNb is the transpose of TTNb
!continue
!""""""""""""""""""""""""""""""""""""""""""""""
!
q=0
!=============================================
!
Open (1240,file='temp240.dat',status='old') !reading temp240.dat (generated by Sortx123) which contains 4 distances (d213) between e.g., PA(Ga)-NA(Sb or As) & 4 permutation indexes obtained by sorting.
read(1240,*) TT240
T240=RESHAPE(TT240, (/N13,8/), ORDER = (/2,1/))
do i=1,N13
    do j=5,8
!---------------------------------------------
            TNb1(i,j)=TNb(i,j-3)-N13 !Example: TNb(i=1,j-3=2)=element_12 in matrix file 111
!            continue
!---------------------------------------------
    Logs23(i,j)=TNb1(i,j).le.N2IN !if TNb1(i,j).le.N2IN, then neighbor is, e.g., atom2(Sb), else neighbor is atom3(As).
    If(Logs23(i,j)) then
        if(T240(i,j-4) .le. Rcut(Rstart)) then !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
        alfa1(i,j)=ac12 !atom1-atom2 bond
        beta1(i,j)=bc12 !atom1-atom2 bond
        did1(i,j)=dc12  !atom1-atom2 bond length
        else
        alfa1(i,j)=0 !cancels contribution to Uel, DU if rpn>Rcut(Rstart) 
        beta1(i,j)=0 ! -II-
        did1(i,j)=dc12  !atom1-atom2 bond length
       end if        
    Else
       if(T240(i,j-4) .le. Rcut(Rstart)) then  !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
!@         if(T240(i,j-4) .le. 2.7) then  !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
        alfa1(i,j)=ac13 !atom1-atom3 bond
        beta1(i,j)=bc13 !atom1-atom3 bond
        did1(i,j)=dc13  !atom1-atom3 bond length
        else
        alfa1(i,j)=0 !cancels contribution to Uel, DU if rpn>Rcut(Rstart) 
        beta1(i,j)=0 !-II-
        did1(i,j)=dc13  !atom1-atom3 bond length
        end if        
    End If
!-----------------------------------------
!
        q=q+1
        alfa(q)=alfa1(i,j);beta(q)=beta1(i,j);did(q)=did1(i,j);dpn(q)=T240(i,j-4); !nghb(q)=nghb1(i,j)    
write(551,*) alfa(q),beta(q),did(q),dpn(q) ! used in EnConfig()
3101 Format(4F12.6,2I2,I7)
    end do
end do
close(1240)
!continue
!=============================================
!
Open (1260,file='temp260.dat',status='old') !reading temp260.dat (generated by Sortx123) which contains 4 distances (d21) between PA(Sb)-NA(Ga) & 4 permutation indexes obtained by sorting.
read(1260,*) TT260
T260=RESHAPE(TT260, (/N2IN,8/), ORDER = (/2,1/))
do i=N13+1,N13+N2IN
    do j=5,8
!---------------------------------------------
            if(T260(i-N13,j-4) .le. Rcut(Rstart)) then !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
            alfa2(i,j)=ac12 !atom2-atom1 bond
            beta2(i,j)=bc12 !atom2-atom1 bond
            did2(i,j)=dc12  !atom2-atom1 bond length
            else
            alfa2(i,j)=0 !cancels contribution to Uel & to DU if rpn>Rcut(Rstart)
            beta2(i,j)=0 !-II-
            did2(i,j)=dc12  !atom2-atom1 bond length
            end if
!---------------------------------
!            
        q=q+1
        alfa(q)=alfa2(i,j);beta(q)=beta2(i,j);did(q)=did2(i,j);dpn(q)=T260(i-N13,j-4);
write(551,*) alfa(q),beta(q),did(q),dpn(q) ! used in EnConfig()
if (alfa(q)==0) then
    end if
    end do
end do
close(1260)
continue
!=============================================
!
Open (1280,file='temp280.dat',status='old') !reading temp280.dat (generated by Sortx123) which contains 4 distances (d31) between PA(As)-NA(Ga) & 4 permutation indexes obtained by sorting.
read(1280,*) TT280
T280=RESHAPE(TT280, (/N4OUT,8/), ORDER = (/2,1/))
do i=N13+N2IN+1,N13+N2IN+N4OUT
    do j=5,8
!---------------------------------------------
            if(T280(i-N13-N2IN,j-4) .le. Rcut(Rstart)) then !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
!@            if(T280(i-N13-N2IN,j-4) .le. 2.7) then !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
            alfa3(i,j)=ac13 !atom3-atom1 bond
            beta3(i,j)=bc13 !atom3-atom1 bond
            did3(i,j)=dc13  !atom3-atom1 bond length
            else
            alfa3(i,j)=0 !cancels contribution to Uel & to DU if rpn>Rcut(Rstart)
            beta3(i,j)=0 !-II-
            did3(i,j)=dc13  !atom3-atom1 bond length
            end if            
!---------------------------------
!            
        q=q+1
        alfa(q)=alfa3(i,j);beta(q)=beta3(i,j);did(q)=did3(i,j);dpn(q)=T280(i-N13-N2IN,j-4); 
write(551,*) alfa(q),beta(q),did(q),dpn(q) ! used in EnConfig()
    if (alfa(q)==0) then
    end if
    end do
end do
!
close(1280)
!""""""""""""""""""""""""""""""""""""""""""""""
End Subroutine abdiddpn
!****************************************************
!
Subroutine EnConfig(QD,x,Uel,DUel,lbfg,Rcut,Rstart)
!Calculate elastic energy Uel & the gradient DUel for an atomic (x) config coords; lbfg is introduced to count the loop # in which EnConfig(..) enters; 
!Comments are for GaSb/GaAs,  InAs/GaAs, Si/C; for Si/C the atomic structure is Si(At1&At2)/C(At3&At4).
use DataType
integer, parameter :: dp = kind(1.0d0)
Real(dp):: T1(N13,3),T2(N13+1:N13+N2IN,3),T3(N13+N2IN+1:N13+N2IN+N4OUT,3),T23(N24,3) !lists of, e.g., coords of Ga(T1),Sb(T2),As(T3), and Sb+As(T23).
Real(dp):: T240(N13,8),TT240(N13,8)
Real(dp):: rn(4*(N13+N2IN+N4OUT),3),rp(N13+N2IN+N4OUT,3) !NA, PA coords.
Real(dp):: alfa(4*(N13+N2IN+N4OUT)),beta(4*(N13+N2IN+N4OUT)),did(4*(N13+N2IN+N4OUT)),dpn(4*(N13+N2IN+N4OUT)) !introduced to build a table which collects together all elastic parameters, bulk distances, PA-NA distances; the terms entering in Uel & DUel expressions are easier addressed from the table.
!*integer:: nghb1(N13,5:8) !to be activated if if file 501 is going to be written; NA type for Ga atoms.
!*Integer::nghb(4*N13) !to be activated if if file 501 is going to be written.
      Integer:: TTNb1(N13,8),TNb1(N13,8),TTNb2(N2IN,8),TNb2(N2IN,8),TTNb3(N4OUT,8),TNb3(N4OUT,8)
      Integer:: TTNb(N13+N2IN+N4OUT,5),TNb(N13+N2IN+N4OUT,5)
      Integer::i,j,t, Rstart
      Logical::Logs23(N13,5:8)
Real(dp):: x(3*(N13+N2IN+N4OUT)), Rcut(5)
Real(dp):: PA2(4*N13,3), PA3(4*N2IN,3),PA4(4*N4OUT,3)
!
Real(dp):: U1,ruLi(3),U2,ruLj(3),Uel
Real(dp):: rdLk(3) 
Real(dp):: DU11p(3),DU12p(3),DU11(1:(N13+N2IN+N4OUT),3),DU12(1:(N13+N2IN+N4OUT),3),DU1(1:(N13+N2IN+N4OUT),3)
Real(dp):: rdij(3),rdLi(3),rdLj(3)
Real(dp):: DU21p(3),DU22p(3),DU21(1:(N13+N2IN+N4OUT),3),DU22(1:(N13+N2IN+N4OUT),3),DU2(1:(N13+N2IN+N4OUT),3)
Real(dp):: DUel(1:(N13+N2IN+N4OUT),3)
Real(dp):: DUelt(1:(N13+N2IN+N4OUT),3)
!
integer::k,L,LL,q,qq,jj,ii,nond,lbfg, qqq, q1, q2, QD !, stgy
Real(dp):: cos
Real(dp):: abdd(4*(N13+N2IN+N4OUT),4), abddR(4*(N13+N2IN+N4OUT),4)
!****************************************************
cos=-0.3338068592337717d0 !cos = Cos[109.5 Degree];
!
!I.  One collects the data for Uel & DUel calculus
!I.1 Firstly, atom coords:
!continue
!
do i=1,N13
    T1(i,1)=x(3*(i-1)+1);T1(i,2)=x(3*(i-1)+2);T1(i,3)=x(3*(i-1)+3) !Ga atom coords
end do
!write(91,*)T1
!
do i=N13+1,N13+N2IN
    T2(i,1)=x(3*(i-1)+1);T2(i,2)=x(3*(i-1)+2);T2(i,3)=x(3*(i-1)+3) !Sb atom coords
    T23(i-N13,1)=x(3*(i-1)+1);T23(i-N13,2)=x(3*(i-1)+2);T23(i-N13,3)=x(3*(i-1)+3) !Sb atom coords
end do
!write(92,*)T2

do i=N13+N2IN+1,N13+N2IN+N4OUT
    T3(i,1)=x(3*(i-1)+1);T3(i,2)=x(3*(i-1)+2);T3(i,3)=x(3*(i-1)+3) !As atom coords
    T23(i-N13,1)=x(3*(i-1)+1);T23(i-N13,2)=x(3*(i-1)+2);T23(i-N13,3)=x(3*(i-1)+3) !As atom coords
end do
!write(93,*)T3
!---------------------------------------------------------------
!
!continue
    rewind(111) !file 111 provides the indexes of each atom and its first 4 neighbors for the initial configuration
    read(111,*)TTNb
    TNb=RESHAPE(TTNb, (/N13+N2IN+N4OUT,5/), ORDER = (/2,1/)) !TNb is the transpose of TTNb
!continue
!===============================================
!
!I.2 Secondly, to x coords of each atom one adds the neighbor coords
!*open(unit=501,file='temp501.dat',status='replace') !for tests & DerivExist(..).; PA position & its first 4 NAs in final configuration & ordering
!------------------------------------------------
!
rewind(551)
read(551,*) abdd
    abddR=RESHAPE(abdd, (/4*(N13+N2IN+N4OUT),4/), ORDER = (/2,1/)) !abddR is the transpose of TTNb
!continue
do i=1,4*(N13+N2IN+N4OUT)
alfa(i)=abddR(i,1)
beta(i)=abddR(i,2)
did(i)=abddR(i,3)
dpn(i)=abddR(i,4)
end do
!
q=0;qqq=0
!=================================================
!*: For GaSb/GaAs: Ga; For InAs/GaAs: As; For Si/C: Si(N1IN_At1)+C(N13-N1IN_At3 OUT QD) as PA.
q1=0;q2=0
DO i=1,N13
    do j=5,8
!---------------------------------------------
            TNb1(i,j)=TNb(i,j-3)-N13 !Example: TNb(i=1,j-3=2)=element_12 in matrix file 111
!            continue
!---------------------------------------------
!*ACTIVATE the below 10 commands + 'nghb(q)=nghb1(i,j)'  if file 501 is going to be written:
!    Logs23(i,j)=TNb1(i,j).le.N2IN !if TNb1(i,j).le.Nat2, then neighbor is atom2(Sb), else neighbor is atom3(As).
!    If(Logs23(i,j)) then
!        if(T240(i,j-4) .le. Rcut(Rstart)) then !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
!        nghb1(i,j)=2     !neighbor type
!       end if        
!    Else
!        if(T240(i,j-4) .le. Rcut(Rstart)) then  !Rcut(Rstart)=max search radius for neighbors in the Rstart-th minimization cycle
!        nghb1(i,j)=3     !neighbor type
!        end if        
!    End If
!-----------------------------------------
!
    t=TNb1(i,j)
        q=q+1
        qq=(q-1)/4+1     
        rp(qq,1)=T1(i,1);rp(qq,2)=T1(i,2);rp(qq,3)=T1(i,3)  
        rn(q,1)=T23(t,1);rn(q,2)=T23(t,2);rn(q,3)=T23(t,3);
        dpn(q)=dsqrt((rp(qq,1)-rn(q,1))**2+(rp(qq,2)-rn(q,2))**2+(rp(qq,3)-rn(q,3))**2) 
!*        nghb(q)=nghb1(i,j)  !to be activated if if file 501 is going to be written.      
!*write(501,3101) alfa(q),beta(q),did(q),dpn(q),rp(qq,1),rp(qq,2),rp(qq,3),rn(q,1),rn(q,2),rn(q,3),1,nghb(q), q !for tests & DerivExist(..).
!*3101 Format(10F12.6,2I2,I7)
    end do
END DO 
!continue
!=====================================================
!
!**: For GaSb/GaAs: Sb; For InAs/GaAs: In; For Si/C: Si - as PA.
qqq=0
do i=N13+1,N13+N2IN
    do j=5,8
!---------------------------------------------
            TNb2(i-N13,j)=TNb(i,j-3)
        t=TNb2(i-N13,j)
!---------------------------------
!            
        q=q+1
        qq=(q-1)/4+1
        rp(qq,1)=T2(i,1);rp(qq,2)=T2(i,2);rp(qq,3)=T2(i,3)
        rn(q,1)=T1(t,1);rn(q,2)=T1(t,2);rn(q,3)=T1(t,3)
        dpn(q)=dsqrt((rp(qq,1)-rn(q,1))**2+(rp(qq,2)-rn(q,2))**2+(rp(qq,3)-rn(q,3))**2)
!write(501,3101) alfa(q),beta(q),did(q),dpn(q),rp(qq,1),rp(qq,2),rp(qq,3),rn(q,1),rn(q,2),rn(q,3),2,1, q !for tests & DerivExist(..).
    end do
end do
!continue
!====================================================
!
!***: For GaSb/GaAs: As; For InAs/GaAs: As; For Si/C: C as PA.
qqq=0
do i=N13+N2IN+1,N13+N2IN+N4OUT
    do j=5,8
!---------------------------------------------
            TNb3(i-N13-N2IN,j)=TNb(i,j-3)
        t=TNb3(i-N13-N2IN,j)  
!---------------------------------
!            
        q=q+1
        qq=(q-1)/4+1 
        rp(qq,1)=T3(i,1);rp(qq,2)=T3(i,2);rp(qq,3)=T3(i,3)
        rn(q,1)=T1(t,1);rn(q,2)=T1(t,2);rn(q,3)=T1(t,3);
        dpn(q)=dsqrt((rp(qq,1)-rn(q,1))**2+(rp(qq,2)-rn(q,2))**2+(rp(qq,3)-rn(q,3))**2)
!write(501,3101) alfa(q),beta(q),did(q),dpn(q),rp(qq,1),rp(qq,2),rp(qq,3),rn(q,1),rn(q,2),rn(q,3),3,1, q !for tests & DerivExist(..). 
    end do
end do
!continue
!
!close (501)
!****************************************************
!
!II.  Next one computes Uelastic energy (Uel) and gradient of elastic energy DUel (see notes U_der_math.pdf)
!
    U1=0; U2=0
loop_1: DO L=1,4*(N13+N2IN+N4OUT),4 
    DU=0
    LL=L/4+1
    DU11p=0;DU12p=0;DU11=0;DU12=0;DU1=0;
    DU21p=0;DU22p=0;DU21=0;DU22=0;DU2=0;
    nond=0
        !--------------------    
    Do i=1,4*(N13+N2IN+N4OUT)
    !* For U1:
        if((i.gt.L-1).and.(i.lt.L+4))then
        ruLi=rp(LL,:)-rn(i,:) !periodicity by 4 of groups of coords
        U1=U1+3*alfa(i)/(8*did(i)**2)*&
            (dot_product(ruLi,ruLi)-did(i)**2)**2
   !     continue 
    !* For U2:
    do jj=L,L+3 
        ruLj=rp(LL,:)-rn(jj,:)!periodicity by 4 of groups of coords
        if(i.ne.jj)then
        U2=U2+3*dsqrt(beta(i)*beta(jj))/(8*did(i)*did(jj))*&
            (dot_product(ruLi,ruLj)-did(i)*did(jj)*cos)**2
        end if
   !     continue
    end do      
        end if
!--------------------------------     
        if ((rp(LL,1).ne.rn(i,1)).or.(rp(LL,2).ne.rn(i,2)).or.(rp(LL,3).ne.rn(i,3))) then
        nond=nond+1 !count to check the derivative existence; see below
        end if
!--------------------------------  
!        
    !* For DU11:
    if((rp(LL,1)==rn(i,1)).and.(rp(LL,2)==rn(i,2)).and.(rp(LL,3)==rn(i,3)))then   !finds rp(<->rim) which is a neighbor rn(<->rLq)  
        ii=(i-1)/4+1 !ii is the index of principal rp(ii,:) for rn(i,:)
        rdLi=rp(ii,:)-rn(i,:) !periodicity by 4 of groups of coords; (<->rim-rLq)
        DU11p=DU11p-4*3*alfa(i)/(8*did(i)**2)*&
             (dot_product(rdLi,rdLi)-did(i)**2)*rdLi  !checked notes; see for check file 301 or 501  with small # of atoms.  
!    continue
    !* For DU21:    
        k=i-mod(i,4)
        if (k==i)then
             k=k-3
        else
             k=i-mod(i,4)+1
        end if             
        do j=k,k+3             
            if(j.ne.i) then     !-----
                ii=(i-1)/4+1 
         rdij=rp(ii,:)-rn(j,:) !periodicity by 4 of groups of coords; rp(ii,:)<->rim; rn(j,:)<->rjn
      DU21p=DU21p+4*3*dsqrt(beta(i)*beta(j))/(8*did(i)*did(j))*&
           (dot_product(rdLi,rdij)-did(i)*did(j)*cos)*(-rdij) !checked notes
   !        continue
            end if              !-----
    !        continue
        end do
            !-----------       
    end if
    end Do
!--------------------------------     
    if (nond==4*(N13+N2IN+N4OUT))then
    Print*,'Not-defined derivative for the atom',LL, 'coords:',rp(LL,:)
    end if
!--------------------------------     
    DU11(LL,:)=DU11p
    DU21(LL,:)=DU21p
!continue  
!--------------------
    !* For DU12:
    Do j=L,L+3
        rdLj=rp(LL,:)-rn(j,:)
        DU12p=DU12p+4*3*alfa(j)/(8*did(j)**2)*&
             (dot_product(rdLj,rdLj)-did(j)**2)*rdLj !checked notes
!        continue 
    !* For DU22:
        do k=L,L+3
            if(j.ne.k) then               
                rdLj=rp(LL,:)-rn(j,:)
                rdLk=rp(LL,:)-rn(k,:)    
        DU22p=DU22p+4*3*dsqrt(beta(j)*beta(k))/(8*did(j)*did(k))*&
            (dot_product(rdLj,rdLk)-did(j)*did(k)*cos)*rdLk !checked notes
            end if
 !           continue
        end do       
    end Do
    DU12(LL,:)=DU12p 
    DU22(LL,:)=DU22p
!    continue
!--------------------
!
    DU1(LL,:)=DU11(LL,:)/2+DU12(LL,:)/2 !P,Pv1-5,7
!-------------------------------------------------------------------- 
!
    DU2(LL,:)=DU21(LL,:)/2+DU22(LL,:)/2 ! P1-v1,3,4,5,7,8
!-------------------------------------------------------------------- 
!continue
    DUel(LL,:)=DU1(LL,:)+DU2(LL,:)
!
end DO loop_1
!
    Uel=U1/2+U2
!-------------------------------------------------------------------- 
!
End Subroutine EnConfig
!******************************************************************